import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { ThemeProvider } from '@mui/material/styles'
import { theme } from '@/core/application/theme/theme'
import './globals.css'
import { roboto, vazir } from '@/core/application/styles/font'
import { StoreProvider } from '@/core/libraries/redux/provider'

export const metadata: Metadata = {
  title: 'jobs kit by sanaz zahedi',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html dir="rtl" lang="en">
      <body className={`${vazir.variable} , ${roboto.variable}}`}>
        <AppRouterCacheProvider>
          <StoreProvider>
            <ThemeProvider theme={theme}>{children}</ThemeProvider>
          </StoreProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
